variables:
  IMAGE_WEBHOOK_URL: $CI_SERVICE_URL/webhook/gitlabProjects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/images
  imageTag: $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME-$DEPLOY_TIME_TAG-$CI_PIPELINE_ID


stages:
  - lint_code
  - push_image
  - push_oss
  - deploy

cache:
  key: "${CI_COMMIT_REF_NAME}"
  paths:
    - dist

lint_code:
  image: registry-sz.vipthink.net/devops-base/node-sonar:1.3
  stage: lint_code
  before_script:
    - if [ ! -f .env ]; then touch .env; fi
    - if [ "$IS_PUSH_OSS" == "1" ]; then echo -e "$CI_ENV_VARIBLES" > .env && echo -e "PUBLIC_PATH=$PUBLIC_PATH" >> .env; fi
    - cat .env
    - yarn
  script:
    - npm run lint
    - npm run sonar:scan
  after_script:
    - npm run build
  tags:
    - devops-ci
  artifacts:
    expire_in: 3 hrs
    paths:
      - ./dist

push_image:
  variables:
    DOCKER_TLS_CERTDIR: ""
  image: docker:20.10.2
  stage: push_image
  services:
    - docker:20.10.2-dind
  tags:
    - devops-ci
  before_script:
    - docker info
  script:
    - docker build -t $CI_REGISTRY_IMAGE_DIR:${imageTag} .
    - docker push $CI_REGISTRY_IMAGE_DIR:${imageTag}
    - wget --post-data "imageTag=$imageTag" $IMAGE_WEBHOOK_URL
  only:
    variables:
      - $IS_PUSH_IMAGE == "1"

push_oss:
  stage: push_oss
  image: rihel/ossutil:1.0
  tags:
    - devops-ci
  before_script:
    - export OSS_ENDPOINT=$OSS_ENDPOINT
    - export OSS_ACCESS_KEY_ID=$OSS_ACCESS_KEY_ID
    - export OSS_ACCESS_KEY_SECRET=$OSS_ACCESS_KEY_SECRET
    - ossutil64 config --endpoint ${OSS_ENDPOINT} --access-key-id ${OSS_ACCESS_KEY_ID} --access-key-secret ${OSS_ACCESS_KEY_SECRET} --language CH
  script:
    - ossutil64 cp -r dist oss://$BUCKNAME/${UPLOAD_PATH}/${imageTag}
    - wget --post-data "imageTag=$imageTag" $IMAGE_WEBHOOK_URL
  only:
    variables:
      - $IS_PUSH_OSS == "1"
      
deploy:
  stage: deploy
  image: rihel/maven:3.6.3-jdk-8
  tags:
    - devops-ci
  script:
    - echo $imageTag
    - wget --header="Authorization:$AUTH_TOKEN" --post-data="pipelineId=$CI_PIPELINE_ID&ref=$CI_COMMIT_REF_NAME&imageName=$imageName&tag=$imageTag&deployVersion=$deployVersion&description=$description&deployParams=$deployParams&envName=$envName&deployType=$deployType" $DEPLOY_WEBHOOK_URL
  only:
    variables:
      - $IS_DEPLOY == "1"

