#!/usr/bin/env bash

# files
files=$(git diff --cached --name-only | egrep ".(js|cjs|mjs|ts|jsx|tsx|vue)$")
# -deleted
for file in $files; do
  if [[ ! -f $file ]]; then
    files=$(echo "$files" | egrep -v "^$file$")
  fi
done
# !files
files=$(echo "$files" | egrep -v "^$")
if [[ -z $files ]]; then
  exit 0
fi

# eslint
eslint="./node_modules/.bin/eslint"
if [[ ! -f $eslint ]]; then
  exit 0
fi

# fix
# -f stylish unix visualstudio codeframe
rs=$(npx eslint $files --fix)
rs=$(npx eslint $files --quiet -f=unix)
error=$?

# add again
git add $files

# error?
if [[ $error != 0 ]]; then
  output="
请修复问题代码之后再提交
[1;31m-----------------------------------------------[0m
[1;31m
$rs
[0m
[1;31m-----------------------------------------------[0m
by: https://github.com/wushufen/commit-lint.git

[1;31m请修复问题代码之后再提交[0m"
  # output=${output//error/[1;31merror[0m}
  # output=${output//Error/[1;31mError[0m}
  # output=${output//ERROR/[1;31mERROR[0m}

  echo "$output"

  exit 1
fi
